In [ ]:
#Numpy
#numerical pyrhon
#고성능 수치계산을위한 라이브러리
#벡터나(한줄로 나열된) 행렬 연산에 편리한 기능 제공
#모든 원소는 같은 자료형만 가능
#대용량 데이터 관리하기 편함

In [12]:
import numpy as np #np는 라이브러리:함수들을 다른사람들이 사용할 수 있도록 책으로 만들어 놓아 우리가 언제든지 사용할 수 잇음
a = np.arange(15)
print(a)
a = a.reshape(3,5)       #reshape는 차원, 차원을 바꾸겠다. 3행 5열 # order = C 행부터 할당, F열부터 할당
print(a)            #1차원에서 2차원으로 바꿈
print(a.shape)
print(a.dtype)
print(a.ndim)     #차원이 몇 차원인지 알려줌
print(a.ndim)  #갯수를 알려줌

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
int32
2
2


In [92]:
b = [-1, 2, 5, -3, 0, 7, -9, 7, -4, -7] #list
print(type(b))
b = np.array(b)
print(type(b))
print(b)

t = (10, 20, 30, 40, 50)
print(type(t))
t = np.array(t)
print(type(t))

s = {10, 20, 30, 40, 50}        #셋은 중복이 안됨    #딕셔너리는 넘페이 안됨. 판다스로 가능
print(type(s))
s =  np.array(s)
print(type(s))



<class 'list'>
<class 'numpy.ndarray'>
[-1  2  5 -3  0  7 -9  7 -4 -7]
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'set'>
<class 'numpy.ndarray'>


In [73]:
print(b.shape)
print(b. ndim)
print(b.dtype)
print(b)

print(np.abs(b))   #절대값 구하는 함수
#print(np.sqrt(b))   #제곱근을 구하는 함수
print(np.sqrt(np.abs(b)))
print(np.square(b))  #제곱
print(np.isnan(b))    #nan이냐 아니냐
print(np.sum(b))     #합계
print(np.mean(b))    #평균
print(np.max(b))     #최대값
print(np.min(b))     #최소값
print(np.argmax(b))  #최대값 인덱스
print(np.argmin(b))  #최소값 인덱스
print(np.sort(b))    #정렬 오름차순
print(np.sort(b)[::-1]) #정렬 내림차순
print(np.median(b))  #중간값, 

(10,)
1
int32
[-1  2  5 -3  0  7 -9  7 -4 -7]
[1 2 5 3 0 7 9 7 4 7]
[1.         1.41421356 2.23606798 1.73205081 0.         2.64575131
 3.         2.64575131 2.         2.64575131]
[ 1  4 25  9  0 49 81 49 16 49]
[False False False False False False False False False False]
-3
-0.3
7
-9
5
6
[-9 -7 -4 -3 -1  0  2  5  7  7]
[ 7  7  5  2  0 -1 -3 -4 -7 -9]
-0.5


In [ ]:
#결측값
# 1, 1, 2, 2, 2, 3, 3, 3, 4, 6, 7, 100 평균을 구하면 맨 뒤 100땜에 평균이 확올라감. 
# 이때 중간값을 구함. 구하기 위해선 정렬이 돼 있어야함.
#짝수일ㄷ땐 중앙값이 2개라 두개를 더하고 이를 반으로 나눠서 구함.

In [28]:
c = [[1, 2, 3], [4, 5, 6]]
print(type(c))
c = np.array(c)
print(type(c))
print(c)
print(np.sum(c))
print(np.sum(c, axis=0)) #axis =0는 행끼리 더함
print(np.sum(c, axis=1)) #axis = 1은 열끼리 더한것 = [[1, 2, 3], [4, 5, 6]]
print(type(c))
c = np.array(c)
print(type(c))
print(c)
print(np.sum(c))
print(np.sum(c, axis=0)) #axis =0는 행끼리 더함
print(np.sum(c, axis=1)) #axis = 1은 열끼리 더한것
print(np.median(c, axis=1))
print(np.max(c, axis=1))

print(np.std(c))  #표준편차
print(np.var(c))  #분산

<class 'list'>
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]
[2. 5.]
[3 6]
1.707825127659933
2.9166666666666665


In [42]:
#element wise
d = [10,20,30,40,50]
# print(d + 2)  #error
d = np.array(d)
print(d + 2)
e = np.array([1,2, 3,4, 5]) #개수만 맞춰 놓으면 하나하나씩 계산 가능
print(d + e)
print(e ** 2)  #제곱
print(d * np.sin(d)) #5개 싸인 구하기
print(d > 35)  #비교 연산자 논리값으로 나오기에 주의
print(np.subtract(d, e)) #빼기
print(np.multiply(d, e)) #곱하기
print(np.divide(d, e))  #나누기

[12 22 32 42 52]
[11 22 33 44 55]
[ 1  4  9 16 25]
[ -5.44021111  18.25890501 -29.64094872  29.80452642 -13.11874269]
[False False False  True  True]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


In [56]:
f = np.array([[0, 1], [1, 1]])
g = np.array([[2, 0], [3, 4]])
print(f*g)
print(f @ g) #행렬곱
print(np.dot(f, g)) #행렬곱,함수도 제공함을 보여줌

[[0 0]
 [3 4]]
[[3 4]
 [5 4]]
[[3 4]
 [5 4]]


In [80]:
h = np.zeros(10) #방이 10개짜리 열 만들어줌
print(h)
i = np.zeros((5, 5)) #열이 5, 행이5개
print (i)
j = np.ones(10) #곱셈을 할때 자주 사용
print(j)
# k = np.random.random(10)
# print(type(k))
# print(k)
k = np.random.random(10) * 100
k =[ int(i) for i in k] #반복문을 하나식 꺼내서 반복문을 돌리는 방법, 리스트를 만드는 방법. 다시 np.array하면 바뀜
print(type(k))
print(k)
print(np.random.randint(10, 20))
print(np.random.rand(5, 2))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
<class 'list'>
[43, 87, 97, 23, 87, 27, 30, 79, 28, 62]
11
[[0.95154581 0.59174977]
 [0.76213342 0.9138196 ]
 [0.73259387 0.96125049]
 [0.96682212 0.2528589 ]
 [0.36555058 0.87296932]]


In [90]:
# 슬라이싱
m = [i for i in range(10, 20)]
print(m[0:5])  
print(m[0:5:2])

#ndarray
w = np.arange(10, 20)
print(w[0:5])
print(w[0:5:2])

[10, 11, 12, 13, 14]
[10, 12, 14]
[10 11 12 13 14]
[10 12 14]


In [100]:
# print(r[:, :])는 에러가 남
# print(r[:2][:2])할 시 뒤에가 무조건 열이라 생각하면 안됨 print(s[:2, :2])이렇게 써야함
s = np.arange(1, 16).reshape(3,5)
print(s)
print(s[2][2])
print(s[:2, :2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
13
[[1 2]
 [6 7]]


In [102]:
#전치 행렬
print(s)  #3행 5열
print(s.T)  #5행 3열, 행과 열만 바귀는게 아니라 구조도 바뀜

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [ ]:
#배열 여러개를 합치고 쪼개기

In [106]:
a = [1, 2, 3]
b = [4, 5, 6]
for ab in zip(a, b):  #리스트를 합칠때 zip함수 사용, 합친 값을 튜플로 돌림
    print(ab)
print(list(zip(a, b)))
print( a + b) #리스트는 걍 합치기 써도 됨
#단 print(a + 2)는 에러람. 리스트는 더하기안됨

(1, 4)
(2, 5)
(3, 6)
[(1, 4), (2, 5), (3, 6)]


In [122]:
# c = np.random.rand(2, 2) 
# print(c)
c = np.floor(np.random.rand(2, 2) * 100) 
print(c)
d = np.floor(np.random.rand(2, 2) * 100) 
print(d)
#stack 합치는 함수
print(d)
print(np.hstack((c,d))) #가로로 합침
print(np.vstack((c,d))) #세로로 합침
print(c + d)   #앤 그냥 연산해버림 그래서 stack써야함
#앤 print(a + 2) 가능

[[48. 11.]
 [91.  9.]]
[[98. 81.]
 [59. 54.]]
[[98. 81.]
 [59. 54.]]
[[48. 11. 98. 81.]
 [91.  9. 59. 54.]]
[[48. 11.]
 [91.  9.]
 [98. 81.]
 [59. 54.]]
[[146.  92.]
 [150.  63.]]


In [128]:
e = np.floor(np.random.rand(2, 15) * 100)
print(e)
print(np.hsplit(e, 3)) #3개로 자름
for arr in np.hsplit(e, 3):
    print(arr)
for arr in np.hsplit(e, (3, 7)): #자를 위치[0:3] [3:7]
    print(arr)

[[22. 31. 96. 84. 42. 10. 30. 49. 34. 55. 78. 64.  0. 48. 70.]
 [43. 66.  4. 91. 86. 43. 13. 45. 21. 84.  7. 94. 36. 55. 68.]]
[array([[22., 31., 96., 84., 42.],
       [43., 66.,  4., 91., 86.]]), array([[10., 30., 49., 34., 55.],
       [43., 13., 45., 21., 84.]]), array([[78., 64.,  0., 48., 70.],
       [ 7., 94., 36., 55., 68.]])]


In [140]:
f = np.array([1, 2, 3, 4, 5])
g = np.array(['A','B', 'C', 'D', 'E'])
h = np.array([True, True, False, False, True])
# 삼항연산        조건? 참 : 거짓
#                  참 if조건 else거짓
##where절
print([x if z else y for x, y, z in zip(f, g, h)])
print(np.where(h, f, g))
print(np.where(f < 3, '작다', '크다'))
print(np.where(h, '참', '거짓'))

[1, 2, 'C', 'D', 5]
['1' '2' 'C' 'D' '5']
['작다' '작다' '크다' '크다' '크다']
['참' '참' '거짓' '거짓' '참']


In [ ]:
i = np.arange(10)
#np.save(파일명, i)
#ii - np.load('i.py파일명임')
# print(type(ii))

# j = np.arange(10)
# l = np.arange(10)
# np.savez('jk.npz, x=j, y=k')
# jk = np.load('jk.npz')
# print(type(jk))
# print(jk['x'])
# print(jk['y'])