In [ ]:
#Numpy
#numerical pyrhon
#고성능 수치계산을위한 라이브러리
#벡터나(한줄로 나열된) 행렬 연산에 편리한 기능 제공
#모든 원소는 같은 자료형만 가능
#대용량 데이터 관리하기 편함

In [37]:
import numpy as np #np는 라이브러리:함수들을 다른사람들이 사용할 수 있도록 책으로 만들어 놓아 우리가 언제든지 사용할 수 잇음
a = np.arange(15)
print(a)
a = a.reshape(3,5)       #reshape는 차원, 차원을 바꾸겠다. 3행 5열 # order = C 행부터 할당, F열부터 할당
print(a)            #1차원에서 2차원으로 바꿈
print(a.shape)
print(a.dtype)
print(a.ndim)     #차원이 몇 차원인지 알려줌
print(a.ㅊ)  #갯수를 알려줌

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
int32
2
15


In [55]:
b = [-1, 2, 5, -3, 0, 7, -9, 7, -4, -7] #list
print(type(b))
b = np.array(b)
print(type(b))

t = (10, 20, 30, 40, 50)
print(type(t))
t = np.array(t)
print(type(t))

s = {10, 20, 30, 40, 50}        #셋은 중복이 안됨    #딕셔너리는 넘페이 안됨. 판다스로 가능
print(type(s))
s =  np.array(s)
print(type(s))



<class 'list'>
<class 'numpy.ndarray'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'set'>
<class 'numpy.ndarray'>


In [73]:
print(b.shape)
print(b. ndim)
print(b.dtype)
print(b)

print(np.abs(b))   #절대값 구하는 함수
#print(np.sqrt(b))   #제곱근을 구하는 함수
print(np.sqrt(np.abs(b)))
print(np.square(b))  #제곱
print(np.isnan(b))    #nan이냐 아니냐
print(np.sum(b))     #합계
print(np.mean(b))    #평균
print(np.max(b))     #최대값
print(np.min(b))     #최소값
print(np.argmax(b))  #최대값 인덱스
print(np.argmin(b))  #최소값 인덱스
print(np.sort(b))    #정렬 오름차순
print(np.sort(b)[::-1]) #정렬 내림차순
print(np.median(b))  #중간값

(10,)
1
int32
[-1  2  5 -3  0  7 -9  7 -4 -7]
[1 2 5 3 0 7 9 7 4 7]
[1.         1.41421356 2.23606798 1.73205081 0.         2.64575131
 3.         2.64575131 2.         2.64575131]
[ 1  4 25  9  0 49 81 49 16 49]
[False False False False False False False False False False]
-3
-0.3
7
-9
5
6
[-9 -7 -4 -3 -1  0  2  5  7  7]
[ 7  7  5  2  0 -1 -3 -4 -7 -9]
-0.5
